export const mockCustomer = [
  {
    id: "1",
    name: "Ahmet Yılmaz",
    email: "ahmet.yilmaz@example.com",
    tag: "Yüksek Öncelikli",
    note: "Yeni teklif gönderildi, dönüş bekleniyor.",
    date: "2025-07-29",
    phone: "05321112233",
  },
  {
    id: "2",
    name: "Ayşe Demir",
    email: "ayse.demir@example.com",
    tag: "Öncelikli",
    phone: "05332223344",
  },
  {
    id: "3",
    name: "Mehmet Kara",
    email: "mehmet.kara@example.com",
    tag: "Normal",
    note: "İndirim talebinde bulundu.",
    date: "2025-07-25",
    phone: "05343334455",
  },
  {
    id: "4",
    name: "Fatma Öztürk",
    email: "fatma.ozturk@example.com",
    tag: "Yüksek Öncelikli",
    phone: "05354445566",
  },
  {
    id: "5",
    name: "Mustafa Çelik",
    email: "mustafa.celik@example.com",
    tag: "Öncelikli",
    note: "Randevu oluşturuldu.",
    date: "2025-07-30",
    phone: "05365556677",
  },
  {
    id: "6",
    name: "Elif Şahin",
    email: "elif.sahin@example.com",
    tag: "Normal",
    phone: "05376667788",
  },
  {
    id: "7",
    name: "Emre Yıldız",
    email: "emre.yildiz@example.com",
    tag: "Yüksek Öncelikli",
    note: "Destek talebi açıldı, 2. takip yapılacak.",
    date: "2025-07-31",
    phone: "05387778899",
  },
  {
    id: "8",
    name: "Zeynep Kılıç",
    email: "zeynep.kilic@example.com",
    tag: "Öncelikli",
    phone: "05398889900",
  },
  {
    id: "9",
    name: "Ahsen Demirtaş",
    email: "ahsen.demirtas@example.com",
    tag: "Normal",
    phone: "05319990011",
  },
  {
    id: "10",
    name: "Burak Yavuz",
    email: "burak.yavuz@example.com",
    tag: "Öncelikli",
    note: "İlk görüşme tamamlandı.",
    date: "2025-07-28",
    phone: "05301234567",
  },
];
